#pragma once
// Shadow of lib/I18n/I18n.h + the gitignored, codegen'd I18nKeys.h (generated by
// scripts/gen_i18n.py -- never present in a clean checkout, so this harness cannot rely on
// it existing). Only the 20 StrId keys GameRenderer.cpp actually references (confirmed via
// grep) are listed here. Class shape (I18n::getInstance().get(StrId)) mirrors the real
// lib/I18n/I18n.h exactly so GameRenderer.cpp's real, unmodified call sites typecheck and
// link unchanged. get() returns the key's own name so a wrong-key regression stays visible
// in harness output rather than being silently blanked. This shadow-of-a-codegen'd-file gap
// is logged in /workspace/agent/crosspoint_backlog.md per parent's msg 3946.
#include <cstdint>

enum class StrId : uint8_t {
  STR_DM_ACHIEVEMENTS,
  STR_DM_CORRUPT_NOTICE_BODY,
  STR_DM_CORRUPT_NOTICE_BODY_WHOLERUN,
  STR_DM_CORRUPT_NOTICE_CONTINUE,
  STR_DM_CORRUPT_NOTICE_TITLE,
  STR_DM_DEATH_CAUSE,
  STR_DM_HINT_ACTION,
  STR_DM_HINT_MENU,
  STR_DM_NOTIF_ACHIEVEMENT,
  STR_DM_NOTIF_BOSS_ARRIVAL,
  STR_DM_NOTIF_DEATH,
  STR_DM_NOTIF_FLOOR_ENTRY,
  STR_DM_NOTIF_LEVEL_UP,
  STR_DM_NO_ACHIEVEMENTS,
  STR_DM_STAT_FLOOR,
  STR_DM_STAT_KILLS,
  STR_DM_STAT_LEVEL,
  STR_DM_STAT_TURNS,
  STR_DM_TAP_TO_CONTINUE,
  STR_DM_VICTORY,
  STR_DM_YOU_DIED,
};

class I18n {
 public:
  static I18n& getInstance() {
    static I18n instance;
    return instance;
  }

  I18n(const I18n&) = delete;
  I18n& operator=(const I18n&) = delete;

  const char* get(StrId id) const {
    static const char* kNames[] = {
        "STR_DM_ACHIEVEMENTS",
        "STR_DM_CORRUPT_NOTICE_BODY",
        "STR_DM_CORRUPT_NOTICE_BODY_WHOLERUN",
        "STR_DM_CORRUPT_NOTICE_CONTINUE",
        "STR_DM_CORRUPT_NOTICE_TITLE",
        "STR_DM_DEATH_CAUSE",
        "STR_DM_HINT_ACTION",
        "STR_DM_HINT_MENU",
        "STR_DM_NOTIF_ACHIEVEMENT",
        "STR_DM_NOTIF_BOSS_ARRIVAL",
        "STR_DM_NOTIF_DEATH",
        "STR_DM_NOTIF_FLOOR_ENTRY",
        "STR_DM_NOTIF_LEVEL_UP",
        "STR_DM_NO_ACHIEVEMENTS",
        "STR_DM_STAT_FLOOR",
        "STR_DM_STAT_KILLS",
        "STR_DM_STAT_LEVEL",
        "STR_DM_STAT_TURNS",
        "STR_DM_TAP_TO_CONTINUE",
        "STR_DM_VICTORY",
        "STR_DM_YOU_DIED",
    };
    return kNames[static_cast<uint8_t>(id)];
  }

  const char* operator[](StrId id) const { return get(id); }

 private:
  I18n() = default;
};

#define tr(id) I18n::getInstance().get(StrId::id)
#define I18N I18n::getInstance()
