#pragma once

#include <builtinFonts/caveat_15_regular.h>
#include <builtinFonts/caveat_18_regular.h>
#include <builtinFonts/caveat_27_regular.h>
#include <builtinFonts/caveat_30_regular.h>
#include <builtinFonts/caveat_42_regular.h>

#include <builtinFonts/lexenddeca_10_bold.h>
#include <builtinFonts/lexenddeca_10_bolditalic.h>
#include <builtinFonts/lexenddeca_10_italic.h>
#include <builtinFonts/lexenddeca_10_regular.h>
#include <builtinFonts/lexenddeca_12_bold.h>
#include <builtinFonts/lexenddeca_12_bolditalic.h>
#include <builtinFonts/lexenddeca_12_italic.h>
#include <builtinFonts/lexenddeca_12_regular.h>
#include <builtinFonts/lexenddeca_14_bold.h>
#include <builtinFonts/lexenddeca_14_bolditalic.h>
#include <builtinFonts/lexenddeca_14_italic.h>
#include <builtinFonts/lexenddeca_14_regular.h>
#include <builtinFonts/lexenddeca_16_bold.h>
#include <builtinFonts/lexenddeca_16_bolditalic.h>
#include <builtinFonts/lexenddeca_16_italic.h>
#include <builtinFonts/lexenddeca_16_regular.h>
#include <builtinFonts/bitter_10_bold.h>
#include <builtinFonts/bitter_10_bolditalic.h>
#include <builtinFonts/bitter_10_italic.h>
#include <builtinFonts/bitter_10_regular.h>
#include <builtinFonts/bitter_12_bold.h>
#include <builtinFonts/bitter_12_bolditalic.h>
#include <builtinFonts/bitter_12_italic.h>
#include <builtinFonts/bitter_12_regular.h>
#include <builtinFonts/bitter_14_bold.h>
#include <builtinFonts/bitter_14_bolditalic.h>
#include <builtinFonts/bitter_14_italic.h>
#include <builtinFonts/bitter_14_regular.h>
#include <builtinFonts/bitter_16_bold.h>
#include <builtinFonts/bitter_16_bolditalic.h>
#include <builtinFonts/bitter_16_italic.h>
#include <builtinFonts/bitter_16_regular.h>
#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/notosans_20_bold_digits.h>
#include <builtinFonts/notosans_40_bold_digits.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
