"""PlatformIO post: script hook: stamp our own version into esp_app_desc_t.

Wired as `post:` rather than `pre:` because LIBPATH is only populated once the
framework's own build script has run; at `pre:` time there is nothing to copy.

ESP-IDF embeds an `esp_app_desc_t` at offset 0x30 of the app image; esptool
reports it as "App version" / "Project name".  On this project it is *not*
generated by our build: it lives pre-compiled in `esp_app_desc.c.o` inside
`libesp_app_format.a`, part of the shared `framework-arduinoespressif32-libs`
package under `~/.platformio/packages/`.  Whatever version and project name
were baked in when that package was last built are reported by every firmware
built on the host, regardless of our git state -- which is how a build of
commit 50c9a8ca came to describe itself as `v1.5.0-175-g3e3e043a` /
`crosspoint-phase17-final`, nine commits backwards and under a retired name.

The previous fix patched that shared archive in place per build and restored it
on exit, so it protected exactly one build and left nothing behind.  This does
the same substitution, but against a private copy inside our own build
directory, and puts that copy first on the library search path.  The shared
package is never written to, and every build of this repo stamps itself.
"""

import os
import shutil
import struct
import subprocess
import sys

Import("env")  # noqa: F821  (injected by SCons)

PROJECT_NAME = "crosspoint-llama-pro"
# esp_app_desc_t: magic, secure_version, reserv1[2], version[32], project[32], ...
DESC_MAGIC = 0xABCD5432
VERSION_OFFSET = 16
PROJECT_OFFSET = 48
FIELD_LEN = 32


def warn(msg):
    print(f"WARNING [stamp_app_desc.py]: {msg}", file=sys.stderr)


def project_version(project_dir):
    """The version we want stamped: version.txt, else git describe."""
    path = os.path.join(project_dir, "version.txt")
    if os.path.isfile(path):
        with open(path, encoding="ascii") as handle:
            value = handle.read().strip()
        if value:
            return value
    try:
        return subprocess.check_output(
            ["git", "describe", "--always", "--dirty"],
            text=True, stderr=subprocess.PIPE, cwd=project_dir,
        ).strip()
    except (OSError, subprocess.CalledProcessError) as error:
        warn(f"no version.txt and git describe failed ({error}); descriptor left alone")
        return None


def descriptor_offset(blob):
    """Offset of esp_app_desc_t inside the object file, found by its magic.

    Located by magic rather than by a hardcoded section offset so a framework
    package update that shifts the layout is a miss (and a warning) rather than
    a silent write into the wrong bytes.
    """
    hits = [
        at for at in range(0, len(blob) - 4)
        if struct.unpack_from("<I", blob, at)[0] == DESC_MAGIC
    ]
    if len(hits) != 1:
        warn(f"expected one esp_app_desc magic in the object, found {len(hits)}")
        return None
    return hits[0]


def field(value):
    encoded = value.encode("ascii")
    if len(encoded) >= FIELD_LEN:
        warn(f"'{value}' does not fit in {FIELD_LEN} bytes; truncating")
        encoded = encoded[: FIELD_LEN - 1]
    return encoded + bytes(FIELD_LEN - len(encoded))


def stamp():
    version = project_version(env.subst("$PROJECT_DIR"))  # noqa: F821
    if version is None:
        return

    lib_dirs = [d for d in env["LIBPATH"] if os.path.isfile(  # noqa: F821
        os.path.join(env.subst(str(d)), "libesp_app_format.a"))]  # noqa: F821
    if not lib_dirs:
        warn("libesp_app_format.a not on LIBPATH; descriptor left alone")
        return
    source = os.path.join(env.subst(str(lib_dirs[0])), "libesp_app_format.a")  # noqa: F821

    work = os.path.join(env.subst("$BUILD_DIR"), "appdesc")  # noqa: F821
    os.makedirs(work, exist_ok=True)
    private = os.path.join(work, "libesp_app_format.a")
    shutil.copyfile(source, private)

    member = "esp_app_desc.c.o"
    try:
        subprocess.check_call(["ar", "x", private, member], cwd=work)
    except (OSError, subprocess.CalledProcessError) as error:
        warn(f"could not extract {member} ({error}); descriptor left alone")
        return

    obj = os.path.join(work, member)
    with open(obj, "rb") as handle:
        blob = bytearray(handle.read())
    at = descriptor_offset(blob)
    if at is None:
        return
    blob[at + VERSION_OFFSET: at + VERSION_OFFSET + FIELD_LEN] = field(version)
    blob[at + PROJECT_OFFSET: at + PROJECT_OFFSET + FIELD_LEN] = field(PROJECT_NAME)
    with open(obj, "wb") as handle:
        handle.write(blob)

    try:
        subprocess.check_call(["ar", "r", private, member], cwd=work)
        subprocess.check_call(["ranlib", private], cwd=work)
    except (OSError, subprocess.CalledProcessError) as error:
        warn(f"could not repack the archive ({error}); descriptor left alone")
        return

    # Ours first: the framework asks for -lesp_app_format by name, so the
    # earliest match on the search path wins and the shared copy is untouched.
    env.Prepend(LIBPATH=[work])  # noqa: F821
    print(f"stamp_app_desc.py: {version} | {PROJECT_NAME}")


stamp()
