// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LEXENDDECA_10_FONT_ID (1144677629)
#define LEXENDDECA_12_FONT_ID (1926983473)
#define LEXENDDECA_14_FONT_ID (-1406445118)
#define LEXENDDECA_16_FONT_ID (2019090238)
#define BITTER_10_FONT_ID (-1242223189)
#define BITTER_12_FONT_ID (611815583)
#define BITTER_14_FONT_ID (167846617)
#define BITTER_16_FONT_ID (-1284751464)
#define NOTOSERIF_12_FONT_ID (85340443)
#define NOTOSERIF_14_FONT_ID (-1367885987)
#define NOTOSERIF_16_FONT_ID (1428909134)
#define NOTOSERIF_18_FONT_ID (-501438527)
#define NOTOSANS_12_FONT_ID (2057568286)
#define NOTOSANS_14_FONT_ID (-1589315735)
#define NOTOSANS_16_FONT_ID (1669013660)
#define NOTOSANS_18_FONT_ID (37077304)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (674098198)
#define NOTOSANS_40_BOLD_DIGITS_FONT_ID (207286959)
#define NOTOSANS_20_BOLD_DIGITS_FONT_ID (-866383848)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_40_BOLD_DIGITS_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_20_BOLD_DIGITS_FONT_ID != 0, "Font ID collision with sentinel");
